name: Tests

on: [ push, pull_request ]

jobs:
  lint:
    name: Tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ "3.10" ]
        tox-env: [ "mypy", "flake8", "py" ]
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          pip install --upgrade pip setuptools wheel
          pip install tox
      - name: Check manifest
        run: tox -e ${{ matrix.tox-env }}
